# Generated by Django 4.2 on 2024-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_otp_failed_attempts_otp_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backgroundimage',
            field=models.ImageField(default='default_cover_img.png', upload_to='backgroundpic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='default.png', upload_to='profilepic'),
        ),
    ]
