# Generated by Django 4.2 on 2023-12-08 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_demo_profile_post_otp_like_post_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_time', models.DateField(default=datetime.datetime.now)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
            ],
        ),
    ]
