# Generated by Django 4.2 on 2023-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
